language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project 
memeservices-4c685 — token 1/oVkIR39oWjKECNjDPMP9SuJ-Nb_eNRCsS21byrhEapc